name: Docs Generation

on:
  push:
    branches:
      - master

jobs:
  GenerateDocs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.BOT_SSH_KEY }}

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -r docs-generator/requirements.txt

      - name: Generate docs
        run: |
          python docs-generator/main.py

      - name: Push new docs
        run: |
          git add docs
          git config --global user.email "doc-bot@github-actions.com"
          git config --global user.name "Documentation Bot"
          git commit -m 'CI: Update documentation'
          git push
